"""Added ondelete rule V2

Revision ID: 0ba9d6346c6e
Revises: 567e1dc4386d
Create Date: 2023-10-28 20:27:13.228320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba9d6346c6e'
down_revision: Union[str, None] = '567e1dc4386d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
