"""Add UniqueConstant to FriendShip table

Revision ID: 1b521553b1f6
Revises: f67ad3d3981a
Create Date: 2023-10-18 19:57:33.860795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b521553b1f6'
down_revision: Union[str, None] = 'f67ad3d3981a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'friendships', ['to_user', 'from_user'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships', type_='unique')
    # ### end Alembic commands ###
