"""UserProfile one to one rs

Revision ID: 6c96b1e074d8
Revises: de6fa4fb636d
Create Date: 2023-10-17 18:58:01.065237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c96b1e074d8'
down_revision: Union[str, None] = 'de6fa4fb636d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_profile', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    # ### end Alembic commands ###
