"""Models refactoring

Revision ID: b0dacd0d9173
Revises: 4f881521a128
Create Date: 2023-10-24 18:55:08.947077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0dacd0d9173'
down_revision: Union[str, None] = '4f881521a128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklist', 'initiator_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('blacklist', 'blocked_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friendships', 'to_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friendships', 'from_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('friendships', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'privacy_settings',
               existing_type=postgresql.ENUM('PUBLIC', 'FRIENDS', 'PRIVATE', name='privacysettingsenum'),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'privacy_settings',
               existing_type=postgresql.ENUM('PUBLIC', 'FRIENDS', 'PRIVATE', name='privacysettingsenum'),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friendships', 'is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('friendships', 'from_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('friendships', 'to_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('blacklist', 'blocked_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blacklist', 'initiator_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
