"""FriendShips try to fix relationship 2

Revision ID: de6fa4fb636d
Revises: 2181e4688e37
Create Date: 2023-10-17 01:58:11.828929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6fa4fb636d'
down_revision: Union[str, None] = '2181e4688e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
